# Generated by Django 5.1.5 on 2025-02-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
