# Generated by Django 5.1.5 on 2025-02-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_grade_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='last_submitted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
